### ISSUE TITLE
Crafting and crafting recipe Not Show

### ISSUE THREAD

**Issue by SuryaRajgor** [Kira-NT/nether-chest#1]
not show in the recipe and if we put brick and star it does not show output item if click output box then star and brick remove but nether chest not add in the inventory 
![Screenshot_46](https://user-images.githubusercontent.com/9131487/142558558-8d2dd24a-47b2-42a9-9811-54f476f950a9.png)

**Comment by Kira-NT** [comment]
The issue is obviously not reproducible on its own. May be caused by incompatibilities with other mods

**Comment by SuryaRajgor** [comment]
[Solved]
Problem: Client-side Mod Not Work 
If Clientside and Serverside both work then its work fine
