### ISSUE TITLE
[Suggestion] a way to lock Nether Chest to lock it to specific channel.

### ISSUE THREAD

**Issue by SpiderKolo** [Kira-NT/nether-chest#2]
This is a copy of a comment I wrote on Curseforge page of your mod.
Though that this would be a bit better place for suggestion to be seen:

I have one idea for a chest to make it even more useful for multiplayer servers:

What if there was... like one slot which let's you insert different items on top/front of the chest and depending on item you can access specific channel.
It would be still public chest... anyone who knows code for the channel can access said channel with their Nether Chest.

So... putting a red dye would be a "red dye" channel, iron sword with 5 damage to durability would be "iron sword with 5 damage to durability" and dyed magenta and named "pinkY" leather boots with 39 damage to durability and enchanted with Fire Protection III and Unbreaking I would be... well, that exact channel.

You could go for one slot and make the chest read all the tags from the chest, making named items, books or maps be possibly one of the best candidates for more secured connections, but risk losing all items inside of the connection permanently if you lose all copies for that specific channel while your items are inside of it.

 

In fact - signed books seems to be the most secure way of connecting chests. They have information on who signed the book and if they are the original book, or it's copy, or a copy of a copy...
and you can use that to basically create second ender chest with a risk of loosing all it's contents if you lose said book.

 

With all of that... I think Nether Chest would be much, MUCH more useful than Ender Chest for wireless transportation of items, but also as a bit less secured Ender Chest with a high risk of loosing items if you lose the key.
...which would be an appropriate second use for Nether Star if you ask me.

**Comment by Kira-NT** [comment]
I like, no, I **love** this idea. It's much better than traditional color codes which a lot of mods are using.

I can guarantee, that this will be implemented, but I don't know when :)
