### ISSUE TITLE
[Suggestion] option to limit the channel identifier item thing to items without NBT?

### ISSUE THREAD

**Issue by Dejeh** [Kira-NT/nether-chest#3]
I hope this isn't asking too much; I'm only asking because while giving factions on a server the option to store their items is wonderful, it's very easy to create lots of storage channels if you have the resources (and by simply renaming a piece of paper).

But if you limit it down to unenchanted/unnamed items it creates a risk factor of someone discovering your channel and I think that would be pretty cool :)

**Comment by Kira-NT** [comment]
This will be done, because I need to provide mod users with a way to limit the number of active channels anyway

**Comment by LoganDark** [comment]
After The Flattening it became feasible to treat channels as exclusively the item ID of whatever you put in the channel slot. For example `minecraft:diamond` or `minecraft:red_wool`. This could be a config setting.

**Comment by Kira-NT** [comment]
@LoganDark, could you elaborate, please?

**Comment by LoganDark** [comment]
> @LoganDark, could you elaborate, please?

Before The Flattening (1.13), many items used damage values to mean completely different items, like the golden apple & enchanted golden apple, or all colors of wool having the same ID with a different damage value. But now everything has its own ID, i.e. `golden_apple` vs `enchanted_golden_apple`, `red_wool` vs `blue_wool`, `dirt` vs `podzol` and so on.

Therefore the item ID on its own has become unique enough (as of >=1.13) to be usable as a channel on its own, without having to take into account item damage or NBT (including name or enchantments).

Obviously the ability to make such a unique item that it can't be copied is a very cool idea (i.e. you store all your key items in your ender chest and you're the only one with those items). I don't want that functionality to disappear. I was simply offering an idea for how you could implement a resolution to this issue.

That way, the nether chest wouldn't *reject* items without NBT, it would just act as if there was no NBT at all.

One unresolved concern is how existing storages will be accessed if items with NBT were used to store them before the setting was enabled. Maybe, if items exist under an item with NBT, you allow items to be taken out but not put back in, then when you take all the items out, it changes to the channel without NBT. But that sounds complicated lol

**Comment by Kira-NT** [comment]
Oh, yeah, gotcha. I meant to implement the thingy this exact way
