### ISSUE TITLE
[bug] REI compat

### ISSUE THREAD

**Issue by Dejeh** [Kira-NT/nether-chest#4]
![pot](https://user-images.githubusercontent.com/72144320/154819688-3b16a809-e96c-4f73-a06f-325fb06af354.png)
it doesn't have the italicized mod name below it either. I'm not sure why this is but I'm assuming it's not REI

**Comment by Kira-NT** [comment]
Nope, the mod has nothing to do with REI itself and/or custom recipes that can break it indirectly. Item registration is fully vanilla, nothing that REI cannot (or shouldn't) handle

**Comment by Dejeh** [comment]
Are you sure? This mod is giving an error in the log.
`[ForkJoinPool-1-worker-5/WARN]: The mod "netherchest" contains invalid entries in its mod json:
Unsupported root entry "includes" at line 46 column 13`
I don't know much about this but given it's the only one doing so I'd assume that's why it's not registering properly

**Comment by Kira-NT** [comment]
Yep, absolutely sure. This is not an error, it's a warning. I use `includes` entry in the json metadata, that hasn't been standardized yet, therefore Fabric loader emits a warning (because some developers tend to misspell entries like «licence» instead of «license») and literally nothing more.

**Comment by Dejeh** [comment]
Okay, thanks for the explanation

**Comment by Kira-NT** [comment]
No problems :)
