### ISSUE TITLE
1.19.4 or 1.20?

### ISSUE THREAD

**Issue by allanonmage** [Kira-NT/nether-chest#9]
Will this mod be updated?  According to Modrinth, it's been a year, and while I see lots of downloads on Modrinth, I don't see much going on here on Github.

I have this mod installed in on my survival server and would like to see it carried forward.

Will you be updating the mode to the newer versions?

**Comment by Kira-NT** [comment]
Thank you for your interest in the project! Unfortunately, I cannot provide an ETA for this. Please keep in mind that mod development is an unpaid hobby of mine, so even though I love all my projects and want to keep them alive, it's definitely not the highest priority on my list. Basically, I develop mods when I have time to play Minecraft, and I haven't been able to do that for the past year or so, as you can see. So, yeah, at some point in the future, I will update my mods for sure, but I cannot tell you the exact date when that will happen.

**Comment by allanonmage** [comment]
OK, thanks for clarifying.
